server:
  port: ${port:8080}

spring:
  liquibase:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "somepassword"
    driver-class-name: org.postgresql.Driver