version: "2.19.1"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "somepassword"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"